import { minify } from "html-minifier";
import { prerendering } from "$app/env";

const minification_options = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  decodeEntities: true,
  includeAutoGeneratedTags: false,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: true,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  sortAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  minifyJS: true,
  minifyCSS: true,
};

export async function handle({ request, resolve }) {
  const response = await resolve(request);

  if (prerendering && response.headers["content-type"] === "text/html") {
    response.body = minify(response.body, minification_options);
  }

  return response;
}
